piVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace | default "techtrek" }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
  SECRET_KEY: {{ .Values.secretKey | quote }}