import json
from http.server import BaseHTTPRequestHandler, HTTPServer

HOST = "0.0.0.0"
PORT = 11434


def make_response_array(prompt: str):
    # Minimal mock response: one discount candidate per request.
    return [
        {
            "product_url": "/sample-product",
            "discount_percentage": 10,
            "final_price": 90,
            "reasoning": "mock discount generated by local LLM service",
            "llm_factors": {"source": "mock-llm"},
        }
    ]


class MockLLMHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        if self.path != "/api/generate":
            self.send_error(404, "Not Found")
            return

        content_length = int(self.headers.get("Content-Length", 0))
        raw_body = self.rfile.read(content_length)
        try:
            payload = json.loads(raw_body.decode("utf-8"))
        except json.JSONDecodeError:
            self.send_error(400, "Invalid JSON")
            return

        prompt = payload.get("prompt", "")
        response_text = json.dumps(make_response_array(prompt))
        response_payload = {"text": response_text}
        response_body = json.dumps(response_payload).encode("utf-8")

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(response_body)))
        self.end_headers()
        self.wfile.write(response_body)

    def log_message(self, format, *args):
        # Keep logs minimal in container output.
        pass


if __name__ == "__main__":
    server = HTTPServer((HOST, PORT), MockLLMHandler)
    print(f"Mock LLM server running at http://{HOST}:{PORT}")
    server.serve_forever()
