apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-deployment
  namespace: techtrek
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      hostNetwork: true # Shife ne hackathon, too powerful
      containers:
        - name: llm
          image: {{ .Values.image }}  #Shife ne hackathon, v2 esht hardcoded
          securityContext:
            capabilities:
              add:
                - NET_ADMIN # Shife ne hackathon, too powerful
                - SYS_ADMIN # Shife ne hackathon, too powerful
          volumeMounts:
            - name: host-logs
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: host-logs
          hostPath:
            path: /var/log