import type { Product, ProductListResponse } from '../types';

const BASE = import.meta.env.VITE_API_URL || '/api';

export async function fetchProducts(params: {
  category?: string;
  page?: number;
  limit?: number;
} = {}): Promise<ProductListResponse> {
  const qs = new URLSearchParams();
  if (params.category) qs.set('category', params.category);
  if (params.page) qs.set('page', String(params.page));
  if (params.limit) qs.set('limit', String(params.limit));

  const res = await fetch(`${BASE}/products/?${qs}`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json();
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    external_id: 'p1',
    name: 'Samsung Galaxy S26 Ultra 512GB CobViolet',
    brand: 'Samsung',
    category: 'telefona',
    price_original: 157900,
    final_price: 134215,
    discount_percentage: 15,
    image_url: null,
    product_url: 'https://www.one.al',
    description: 'Flagship Android smartphone with 200MP camera, 6.9" Dynamic AMOLED display, and 5000mAh battery.',
    specs: {
      RAM: '12GB',
      Storage: '512GB',
      Display: '6.9"',
      Camera: '200+12MP',
      Brand: 'Samsung',
      Color: 'CobViolet',
      'Dual SIM': 'Yes',
    },
    is_available: true,
    scraped_at: null,
    created_at: new Date().toISOString(),
    reasoning: 'Based on your postpaid plan usage, you qualify for a loyalty discount.',
    discount_expires_at: null,
  },
  {
    id: '2',
    external_id: 'p2',
    name: 'Samsung Galaxy S26 Ultra 512GB Black',
    brand: 'Samsung',
    category: 'telefona',
    price_original: 157900,
    final_price: null,
    discount_percentage: null,
    image_url: null,
    product_url: 'https://www.one.al',
    description: 'Flagship Android smartphone with 200MP camera system.',
    specs: {
      RAM: '12GB',
      Storage: '512GB',
      Display: '6.9"',
      Color: 'Black',
    },
    is_available: true,
    scraped_at: null,
    created_at: new Date().toISOString(),
    reasoning: null,
    discount_expires_at: null,
  },
  {
    id: '3',
    external_id: 'p3',
    name: 'Samsung Galaxy S26 Ultra 256GB CobViolet',
    brand: 'Samsung',
    category: 'telefona',
    price_original: 138900,
    final_price: 125010,
    discount_percentage: 10,
    image_url: null,
    product_url: 'https://www.one.al',
    description: 'Flagship Android smartphone, 256GB storage variant.',
    specs: {
      RAM: '12GB',
      Storage: '256GB',
      Display: '6.9"',
      Color: 'CobViolet',
    },
    is_available: true,
    scraped_at: null,
    created_at: new Date().toISOString(),
    reasoning: 'Device upgrade recommendation based on your current handset age.',
    discount_expires_at: null,
  },
  {
    id: '4',
    external_id: 'p4',
    name: 'Samsung Galaxy S26 Ultra 256GB Black',
    brand: 'Samsung',
    category: 'telefona',
    price_original: 138900,
    final_price: null,
    discount_percentage: null,
    image_url: null,
    product_url: 'https://www.one.al',
    description: 'Flagship Android smartphone, 256GB Black variant.',
    specs: {
      RAM: '12GB',
      Storage: '256GB',
      Display: '6.9"',
      Color: 'Black',
    },
    is_available: true,
    scraped_at: null,
    created_at: new Date().toISOString(),
    reasoning: null,
    discount_expires_at: null,
  },
  {
    id: '5',
    external_id: 'p5',
    name: 'Apple iPhone 16 Pro Max 256GB Natural Titanium',
    brand: 'Apple',
    category: 'telefona',
    price_original: 165000,
    final_price: 148500,
    discount_percentage: 10,
    image_url: null,
    product_url: 'https://www.one.al',
    description: 'Apple\'s latest flagship with A18 Pro chip and titanium design.',
    specs: {
      Storage: '256GB',
      Display: '6.9"',
      Color: 'Natural Titanium',
      Chip: 'A18 Pro',
    },
    is_available: true,
    scraped_at: null,
    created_at: new Date().toISOString(),
    reasoning: 'Recommended upgrade from your aging device.',
    discount_expires_at: null,
  },
  {
    id: '6',
    external_id: 'p6',
    name: 'Apple Watch Ultra 2 49mm',
    brand: 'Apple',
    category: 'wearables',
    price_original: 89900,
    final_price: null,
    discount_percentage: null,
    image_url: null,
    product_url: 'https://www.one.al',
    description: 'Rugged smartwatch built for extreme environments.',
    specs: {
      Display: '49mm',
      Material: 'Titanium',
      GPS: 'Yes',
      'Water Resistant': '100m',
    },
    is_available: true,
    scraped_at: null,
    created_at: new Date().toISOString(),
    reasoning: null,
    discount_expires_at: null,
  },
  {
    id: '7',
    external_id: 'p7',
    name: 'Samsung Galaxy Watch 7 44mm',
    brand: 'Samsung',
    category: 'wearables',
    price_original: 42900,
    final_price: 38610,
    discount_percentage: 10,
    image_url: null,
    product_url: 'https://www.one.al',
    description: 'Advanced health tracking smartwatch with 3nm chip.',
    specs: {
      Display: '44mm',
      Battery: '40mAh',
      OS: 'Wear OS',
      'Water Resistant': '50m',
    },
    is_available: true,
    scraped_at: null,
    created_at: new Date().toISOString(),
    reasoning: 'Compatible with your Samsung device.',
    discount_expires_at: null,
  },
  {
    id: '8',
    external_id: 'p8',
    name: 'Apple AirPods Pro 2nd Gen',
    brand: 'Apple',
    category: 'wearables',
    price_original: 28900,
    final_price: null,
    discount_percentage: null,
    image_url: null,
    product_url: 'https://www.one.al',
    description: 'Premium ANC earbuds with H2 chip and personalized spatial audio.',
    specs: {
      ANC: 'Yes',
      Battery: '6hr (30hr case)',
      Chip: 'H2',
      Water: 'IPX4',
    },
    is_available: true,
    scraped_at: null,
    created_at: new Date().toISOString(),
    reasoning: null,
    discount_expires_at: null,
  },
];
