image: "helion444/db:latest"

replicaCount: 1

namespace: database

service:
  type: ClusterIP
  port: 5432

env:
  POSTGRES_USER: techtrek
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: techtrek

autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
volumeMounts: []
volumes: []

serviceAccount:
  create: false
  name: ""
