"""initial tables

Revision ID: ddfb1d6adf81
Revises: 
Create Date: 2026-05-22 22:07:02.308360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfb1d6adf81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Enum('telefona', 'wearables', name='productcategory'), nullable=False),
    sa.Column('price_original', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=True)
    op.create_table('scrape_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('products_found', sa.Integer(), nullable=False),
    sa.Column('products_upserted', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='jobstatus'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('plan_type', sa.Enum('prepaid', 'postpaid', name='plantype'), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('subscription_start_date', sa.Date(), nullable=True),
    sa.Column('monthly_spend_avg', sa.Float(), nullable=True),
    sa.Column('data_usage_gb', sa.Float(), nullable=True),
    sa.Column('age_group', sa.Enum('young', 'adult', 'middle', 'senior', name='agegroup'), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('current_device_model', sa.String(length=100), nullable=True),
    sa.Column('current_device_year', sa.Integer(), nullable=True),
    sa.Column('current_device_brand', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_table('discount_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('products_processed', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='jobstatus'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_logs_user_id'), 'discount_logs', ['user_id'], unique=False)
    op.create_table('user_discounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.String(length=500), nullable=True),
    sa.Column('llm_factors', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', 'is_active', name='uq_user_product_active')
    )
    op.create_index(op.f('ix_user_discounts_is_active'), 'user_discounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_discounts_product_id'), 'user_discounts', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_discounts_user_id'), 'user_discounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_discounts_user_id'), table_name='user_discounts')
    op.drop_index(op.f('ix_user_discounts_product_id'), table_name='user_discounts')
    op.drop_index(op.f('ix_user_discounts_is_active'), table_name='user_discounts')
    op.drop_table('user_discounts')
    op.drop_index(op.f('ix_discount_logs_user_id'), table_name='discount_logs')
    op.drop_table('discount_logs')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scrape_logs')
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
