name: Build and Push Frontend Image

on:
  push:
    branches: [ "master" ]
    paths:
      - "frontend/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "frontend/**"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          VERSION=v${{ github.run_number }}
          docker buildx build \
            --load \
            -t helion444/frontend:$VERSION \
            ./frontend

      - name: Login Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: |
          VERSION=v${{ github.run_number }}
          docker push helion444/frontend:$VERSION

      - name: Update Helm tag
        if: github.ref == 'refs/heads/master'
        run: |
          VERSION=v${{ github.run_number }}
          sed -i "s|tag:.*|tag: $VERSION|" helm/frontend/values.yaml

      - name: Commit Helm update
        if: github.ref == 'refs/heads/master'
        run: |
          VERSION=v${{ github.run_number }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/frontend/values.yaml
          git commit -m "ci: update frontend image to $VERSION" || echo "no changes"
          git pull --rebase origin master
          git push